from pathlib import Path
p = Path('script.js')
text = p.read_text(encoding='utf-8')
old = """    checkCoinsAchievement() {\n        if (this.coinsOwned.size === this.coins.length) {\n            mostrarMensagemLateral('🏅 Colecionador de Moedas: comprou todas!', 'bonus', 3500);\n            // registra conquista simples no sistema local\n            this.adicionarConquistaCoins();\n        }\n    },\n\n    adicionarConquistaCoins() {\n        const nomeJogador = localStorage.getItem('jb_chat_username') || 'Jogador';\n        const conquista = {\n            id: 'coins_master',\n            titulo: 'Colecionador de Moedas',\n            icone: '🏅',\n            descricao: 'Comprou todas as moedas especiais',\n        };\n        if (!RankingSystem.conquistasPorJogador[nomeJogador]) {\n            RankingSystem.conquistasPorJogador[nomeJogador] = [];\n        }\n        const lista = RankingSystem.conquistasPorJogador[nomeJogador];\n        if (!lista.some(c => c.id === conquista.id)) {\n            lista.push({ ...conquista, data: new Date().toLocaleDateString('pt-BR') });\n            RankingSystem.saveConquistas();\n        }\n    },"""
new = """    checkCoinsAchievement() {\n        if (this.coinsOwned.size === this.coins.length) {\n            mostrarMensagemLateral('🏅 Colecionador de Moedas: comprou todas!', 'bonus', 3500);\n            // registra conquista simples no sistema local\n            this.adicionarConquistaCoins();\n        }\n    },\n\n    adicionarConquistaCoins() {\n        const nomeJogador = RankingSystem.getCurrentPlayerName();\n        const conquista = {\n            id: 'coins_master',\n            titulo: 'Colecionador de Moedas',\n            icone: '🏅',\n            descricao: 'Comprou todas as moedas especiais',\n        };\n        if (!RankingSystem.conquistasPorJogador[nomeJogador]) {\n            RankingSystem.conquistasPorJogador[nomeJogador] = [];\n        }\n        const lista = RankingSystem.conquistasPorJogador[nomeJogador];\n        if (!lista.some(c => c.id === conquista.id)) {\n            lista.push({ ...conquista, data: new Date().toLocaleDateString('pt-BR') });\n            RankingSystem.saveConquistas();\n        }\n    },"""
if old not in text:
    raise SystemExit('coins block not found')
p.write_text(text.replace(old,new), encoding='utf-8')
print('ok')
